### ISSUE TITLE
The engine "node" is incompatible with this module. Expected version "18.16.1". Got "20.8.1"

### ISSUE THREAD

**Issue by CWSites** [chromaui/chromatic-cli#1002]
**Bug report**

Previously our action was working fine. As of this morning I'm getting the following error.

## Error

```bash
The CLI tried to run your build-storybook script, but the command failed. This indicates a problem with your Storybook. Here's what to do:
    → Command failed: yarn run build-storybook --output-dir /tmp/chromatic--1759-SARwqzIUwEU0 --webpack-stats-json /tmp/chromatic--1759-SARwqzIUwEU0
- Check the Storybook build log printed below.
- Run npm run build-storybook or yarn build-storybook yourself and make sure it outputs a valid Storybook by opening the generated index.html in your browser.
- Review the build-storybook CLI options at https://storybook.js.org/docs/configurations/cli-options/#for-build-storybook
Command failed with exit code 1: yarn run build-storybook --output-dir /tmp/chromatic--17[59]-SARwqzIUwEU0 --webpack-stats-json /tmp/chromatic--1759-SARwqzIUwEU0
error: The engine "node" is incompatible with this module. Expected version "18.16.1". Got "20.8.1"
error Commands cannot run with an incompatible environment.
ℹ Build command:
yarn run build-storybook --output-dir /tmp/chromatic--1759-SARwqzIUwEU0 --webpack-stats-json /tmp/chromatic--1759-SARwqzIUwEU0
ℹ Runtime metadata:
{
  "nodePlatform": "linux",
  "nodeVersion": "20.8.1",
  "packageManager": "yarn",
  "packageManagerVersion": "1.22.22"
}
ℹ Storybook build output:
```

## GitHub Action

```yml
  visual-tests:
    needs: [interaction-tests, changed-files]
    if: ${{ needs.changed-files.outputs.any_changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18.16.1
      - run: yarn
      - uses: chromaui/action@v1
        with:
          node-version: 18.16.1
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          onlyChanged: true
          exitZeroOnChanges: true
```
