### ISSUE TITLE
JSDOM outputs a CSS error, blocking build

### ISSUE THREAD

**Issue by tmeasday** [chromaui/chromatic-cli#103]
The following CSS: 

```css
@ -moz-document url-prefix () {
   @media print {
     .v-content {
       display: block;
     }
   }
}
```

Causes JSDOM to output a CSS parsing error message, which causes us to block the build due to console errors.

I found this super-old issue: https://github.com/jsdom/jsdom/issues/687 which made it seem as if it is fixed. Not sure 🤷‍♂
