### ISSUE TITLE
GitHub Action TurboSnap fails with Storybook 8.2.9

### ISSUE THREAD

**Issue by MoritzWeber0** [chromaui/chromatic-cli#1030]
**Bug report**

When I enable TurboSnap in my GitHub Actions pipeline, the build starts failing with the following output: 

```
Run chromaui/action@latest

Chromatic CLI v11.7.0
https://www.chromatic.com/docs/cli

Authenticating with Chromatic
    → Connecting to https://index.chromatic.com
Authenticated with Chromatic
    → Using project token '****************a3af'
Retrieving git information

ℹ Missing commit detected
When detecting git changes for TurboSnap, we couldn't find the commit ([6](https://github.com/DSD-DBS/capella-collab-manager/actions/runs/10698776349/job/29658913669?pr=1746#step:6:7)59559c) for the most recent build (#383).
To avoid re-snapshotting stories we know haven't changed, we copied from the most recent build (#382) that did have a commit (edb9813) instead.
Found 3 changed files:
  .github/workflows/storybook.yml
  frontend/src/app/general/404/404.component.html
  frontend/test.txt
Retrieved git information
    → Commit '32e2a86' on branch 'storybook-indication'; found 2 parent builds and 3 changed files
Collecting Storybook metadata
Collected Storybook metadata
    → Storybook 8.2.9 for Angular; using the @storybook/angular builder (8.2.9); supported addons found: Links, Essentials, Interactions
Initializing build
Initialized build
    → Build 385 initialized
Building your Storybook
    → Running command: npm run build-storybook -- --output-dir /tmp/chromatic--18[7](https://github.com/DSD-DBS/capella-collab-manager/actions/runs/10698776349/job/29658913669?pr=1746#step:6:8)8-fuF32LhmrRvY --webpack-stats-json /tmp/chromatic--1[8](https://github.com/DSD-DBS/capella-collab-manager/actions/runs/10698776349/job/29658913669?pr=1746#step:6:9)78-fuF32LhmrRvY
    → [*                   ]
The CLI tried to run your build-storybook script, but the command failed. This indicates a problem with your Storybook. Here's what to do:

- Check the Storybook build log printed below.
- Run npm run build-storybook or yarn build-storybook yourself and make sure it outputs a valid Storybook by opening the generated index.html in your browser.
- Review the build-storybook CLI options at https://storybook.js.org/docs/configurations/cli-options/#for-build-storybook

Command failed with exit code 1: npm run build-storybook -- --output-dir /tmp/chromatic--1878-fuF32LhmrRvY --webpack-stats-json /tmp/chromatic--1878-fuF32LhmrRvY
Error: Unknown argument: /tmp/chromatic--1878-fuF32LhmrRvY

ℹ Build command:
npm run build-storybook -- --output-dir /tmp/chromatic--1878-fuF32LhmrRvY --webpack-stats-json /tmp/chromatic--1878-fuF32LhmrRvY

ℹ Runtime metadata:
{
  "nodePlatform": "linux",
  "nodeVersion": "20.13.1",
  "packageManager": "npm",
  "packageManagerVersion": "[10](https://github.com/DSD-DBS/capella-collab-manager/actions/runs/10698776349/job/29658913669?pr=1746#step:6:11).7.0"
}

ℹ Storybook build output:
/home/runner/work/capella-collab-manager/capella-collab-manager/frontend/build-storybook.log

> capellacollab@0.0.0 build-storybook
> ng run capellacollab:build-storybook --output-dir /tmp/chromatic--1878-fuF32LhmrRvY --webpack-stats-json /tmp/chromatic--[18](https://github.com/DSD-DBS/capella-collab-manager/actions/runs/10698776349/job/29658913669?pr=1746#step:6:19)78-fuF32LhmrRvY
    → Command failed: npm run build-storybook -- --output-dir /tmp/chromatic--1878-fuF32LhmrRvY --webpack-stats-json /tmp/chromatic--1878-fuF32LhmrRvY
```

I use the `chromatic/action@latest` step: 

```yml
- name: Run Chromatic
  id: chromatic
  uses: chromaui/action@latest
  with:
    projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
    workingDir: ./frontend
    onlyChanged: true
```

See also: https://github.com/DSD-DBS/capella-collab-manager/blob/main/.github/workflows/storybook.yml

In the build comment, it tries to pass `--webpack-stats-json`. This option doesn't seem to exist anymore in the latest Storybook version and `--stats-json` should be used instead: https://storybook.js.org/docs/api/cli-options

**Comment by cgbl-90** [comment]
hello @MoritzWeber0 tes, the `--webpack-stats-json` option was [renamed to `--stats-json`].(https://github.com/storybookjs/storybook/blob/ab6690632fc8f8e57e363ce632d6676f810ce41c/MIGRATION.md?plain=1#L36) This error log indicates the flag could have been the issue:
```
Command failed with exit code 1: npm run build-storybook -- --output-dir /tmp/chromatic--1878-fuF32LhmrRvY --webpack-stats-json /tmp/chromatic--1878-fuF32LhmrRvY
Error: Unknown argument: /tmp/chromatic--1878-fuF32LhmrRvY
```

**Comment by MoritzWeber0** [comment]
Is there any workaround for this? Couldn't find any limitations that the Chromatic CLI is not compatible with newer versions of Storybook.

**Comment by MoritzWeber0** [comment]
The following workaround with a prebuilt Storybook seems to work: 

```yml
- name: Build Storybook
  run: npx -p @angular/cli ng run capellacollab:build-storybook
  working-directory: ./frontend
- name: Run Chromatic
  id: chromatic
  uses: chromaui/action@latest
  with:
    projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
    workingDir: ./frontend
    storybookBuildDir: ./storybook-static
    onlyChanged: true
```
