### ISSUE TITLE
Github Actions ##[error]non-zero exit code

### ISSUE THREAD

**Issue by ImranAhmed** [chromaui/chromatic-cli#181]
Hi,

Seeing the below in my github actions logs with a failure to deploy. Using `"chromatic": "^5.1.0"`.

```
 Run chromaui/action@v132s
    exitOnceUploaded: true
Run chromaui/action@v1
  with:
    token: ***
    projectToken: ***
    buildScriptName: build-storybook
    exitZeroOnChanges: true
    exitOnceUploaded: true

Chromatic CLI v5.1.0
https://www.chromatic.com/docs/cli

Cannot read property 'scripts' of undefined
##[error]non-zero exit code
```

Build file
```
name: Run Chromatic

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - uses: chromaui/action@v1
              with:
                  token: ${{ secrets.CHROMATIC_ACCESS_TOKEN }}
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
                  buildScriptName: build-storybook
                  exitZeroOnChanges: true
                  exitOnceUploaded: true
```

**Comment by tmeasday** [comment]
Hi @ImranAhmed did you figure this issue out? Sorry it slipped through the cracks.

**Comment by ImranAhmed** [comment]
Hi,

Thanks for chasing up @tmeasday 

Just tried again and got this error.

`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type object
    at readFile (fs.js:295:10)
    at go$readFile (/home/runner/work/_actions/chromaui/action/v1/node_modules/graceful-fs/graceful-fs.js:118:14)
    at readFile (/home/runner/work/_actions/chromaui/action/v1/node_modules/graceful-fs/graceful-fs.js:115:12)
    at /home/runner/work/_actions/chromaui/action/v1/node_modules/universalify/index.js:8:12
    at new Promise (<anonymous>)
    at readFile (/home/runner/work/_actions/chromaui/action/v1/node_modules/universalify/index.js:7:14)
    at Object._readFile (/home/runner/work/_actions/chromaui/action/v1/node_modules/jsonfile/index.js:19:58)
    at Object._readFile [as readFile] (/home/runner/work/_actions/chromaui/action/v1/node_modules/universalify/index.js:20:45)
    at runChromatic (/home/runner/work/_actions/chromaui/action/v1/lib/main.js:66:42)
    at async Promise.all (index 0)`

My build file:


```
name: Run Chromatic

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory:  web-app
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - uses: chromaui/action@v1
              with:
                  token: ${{ secrets.CHROMATIC_ACCESS_TOKEN }}
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
                  buildScriptName: build-storybook
                  exitZeroOnChanges: true
                  exitOnceUploaded: true

```

**Comment by thelfensdrfer** [comment]
I got the same error. I thought the reason could be the checkout@v2 but I still get the same error with this action:

```yml
name: 'Publish storybook to chromatic'

on: push

jobs:
  chromatic:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v1
      - run: 'echo "$FONTAWESOME_AUTH_TOKEN" > .npmrc'
        shell: bash
        env:
          FONTAWESOME_AUTH_TOKEN: ${{ secrets.FONTAWESOME_AUTH_TOKEN }}
      - run: yarn install
      - uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
```

Error:

```
Error: The "path" argument must be one of type string, Buffer, or URL. Received type object
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type object
    at readFile (fs.js:295:10)
    at go$readFile (/home/runner/work/_actions/chromaui/action/v1/node_modules/graceful-fs/graceful-fs.js:118:14)
    at readFile (/home/runner/work/_actions/chromaui/action/v1/node_modules/graceful-fs/graceful-fs.js:115:12)
    at /home/runner/work/_actions/chromaui/action/v1/node_modules/universalify/index.js:8:12
    at new Promise (<anonymous>)
    at readFile (/home/runner/work/_actions/chromaui/action/v1/node_modules/universalify/index.js:7:14)
    at Object._readFile (/home/runner/work/_actions/chromaui/action/v1/node_modules/jsonfile/index.js:19:58)
    at Object._readFile [as readFile] (/home/runner/work/_actions/chromaui/action/v1/node_modules/universalify/index.js:20:45)
    at /home/runner/work/_actions/chromaui/action/v1/action/main.js:120:53
    at step (/home/runner/work/_actions/chromaui/action/v1/action/main.js:44:23)
Error: The "path" argument must be one of type string, Buffer, or URL. Received type object
```
