### ISSUE TITLE
Github action get stuck for 10 minutes

### ISSUE THREAD

**Issue by hikkyu** [chromaui/chromatic-cli#273]
Hi there!

Chromatic step get stuck for 10 minutes. I think 10 minutes is the timeout.
I tried options `exitOnceUploaded: true | "true" ` & `exitZeroOnChanges` but nothing, build always during 10 minutes. Apparently this step only takes 30 secondes. Did I missed something ?

![Capture d’écran 2021-02-05 à 17 00 34](https://user-images.githubusercontent.com/467261/107057411-b8bbae00-67d3-11eb-8e60-b09f619e1537.png)

Here is my Github workflow file : 
```yaml
name: Chromatic

on: push

jobs:
  chromatic-deployment:
    name: Install & Check stories
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-
      - name: Install dependencies
        run: npm i
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: "true"
```
