### ISSUE TITLE
Error on using `skip` in `chromaui/action@v1`

### ISSUE THREAD

**Issue by YuCJ** [chromaui/chromatic-cli#309]
I tried to avoid ui testing when the branch name matches the `nostorybook/**` pattern.
So I used the `skip` option in the `chromaui/action@v1` Github action but failed.

Here is the log of the error:

```
Run chromaui/action@v1
  with:
    token: ***
    projectToken: ***
    autoAcceptChanges: master|develop
    skip: nostorybook/**
    exitZeroOnChanges: true
    storybookBuildDir: storybook-static
  env:
    NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc

Chromatic CLI v5.7.0
https://www.chromatic.com/docs/cli

Authenticating with Chromatic
    → Connecting to https://index.chromatic.com
Authenticated with Chromatic
    → Using project token '********'
Retrieving git information
Skipping build
    → Skipping build for commit d93560e due to --skip
Skipping build
    → Skipped build for commit d93560e due to --skip
Error: Cannot read property 'toString' of undefined
Error: TypeError: Cannot read property 'toString' of undefined
    at /home/runner/work/_actions/chromaui/action/v1/action/main.js:203:58
    at step (/home/runner/work/_actions/chromaui/action/v1/action/main.js:44:23)
    at Object.next (/home/runner/work/_actions/chromaui/action/v1/action/main.js:25:53)
    at fulfilled (/home/runner/work/_actions/chromaui/action/v1/action/main.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Cannot read property 'toString' of undefined
```

And here is an [example workflow](https://github.com/YuCJ/stories-test/runs/2110570870) with its [yml config](https://github.com/YuCJ/stories-test/blob/nostorybook/change-version/.github/workflows/chromatic.yml)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199921881886840/1200545736090204) by [Unito](https://www.unito.io)

**Comment by jandrade** [comment]
I also tried to use the `skip` option and got the same exact problem. I used this option so dependabot would not run tests when updating dependencies. Here's the workflow output: https://github.com/Khan/wonder-blocks/pull/1160/checks?check_run_id=3843007698

Any support is deeply appreciated 🙏

**Comment by jrolfs** [comment]
Revisiting this because I just realized that my workaround (conditionally running the Chromatic GitHub action with a workflow condition) prevents me from being able to configure the Chromatic UI tests as a "required check" in branch protection because the UI tests never run on branches with said condition.

<img width="903" alt="workaround" src="https://user-images.githubusercontent.com/288160/137817358-9751c592-8d6d-425f-929e-ece834b8906f.png">

**Comment by jrolfs** [comment]
Unfortunately, I can't seem to get it working even when providing the environment variables I see being set in the official action:

#### Workaround

```yml
      - name: Publish to Chromatic
        if:
          ${{
            !contains(github.head_ref, 'dependabot-') &&
            !contains(github.head_ref, 'changeset-release')
          }}
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: 'build:storybook:export'

      - name: Skip Chromatic
        if:
          ${{
            contains(github.head_ref, 'dependabot-') ||
            contains(github.head_ref, 'changeset-release')
          }}
        run: yarn chromatic --project-token=$PROJECT_TOKEN --build-script-name='build:storybook:export' --skip
        env:
          PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          CHROMATIC_BRANCH: ${{ github.head_ref }}
          CHROMATIC_SHA: ${{ github.sha }}
          CHROMATIC_SLUG: ${{ github.repository }}
```

#### Run

<img width="869" alt="skip" src="https://user-images.githubusercontent.com/288160/137826230-80b68da4-c09a-4443-9051-57be9f70025a.png">

#### Checks

<img width="899" alt="required" src="https://user-images.githubusercontent.com/288160/137826597-4732116b-2d8a-400d-9c0e-5d998d677802.png">
