### ISSUE TITLE
Support cron in our GitHub action

### ISSUE THREAD

**Issue by tmeasday** [chromaui/chromatic-cli#358]
For example: 

```yml
- name: Publish to Chromatic
  uses: chromaui/action@v1
  # Chromatic GitHub Action options
  with:
  token: ${{ secrets.GITHUB_TOKEN }}
  # 👇 Chromatic projectToken, refer to the manage page to obtain it.
  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
  exitOnceUploaded: true
```

The workflow triggers:

```yml
on:
  push:
  branches-ignore:
  - 'artifactory-release'
  schedule:
  # Attempt build and publish Monday, Wednesday, and Friday at 8:00 CST
  - cron: '0 14 * * 1,3,5'
```

And they are getting this error:

`Error: schedule event is not supported in this action`

I'm not sure why we don't support this, but if it is easy, maybe we can.
