### ISSUE TITLE
GitHub action fails with `Error: Cannot find module 'node:path'`

### ISSUE THREAD

**Issue by Wedvich** [chromaui/chromatic-cli#422]
We use the GitHub action for Chromatic in our CI pipeline, and it stopped working about 30 minutes ago. It now produces the following error on every run:

![image](https://user-images.githubusercontent.com/1078076/137128129-686e53d3-d662-4861-9e84-25cc963c74cf.png)

Here is our workflow:

```yaml
name: 'PR Checks'
on: push

jobs:
  test:
    name: Chromatic QA
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 14.17
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required to retrieve git history

      - name: Use Node.js v14 with Yarn cache
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.NODE_VERSION }}-nodemodules-

      - name: Yarn install
        run: yarn --frozen-lockfile --prefer-offline
        if: |
          steps.cache-node-modules.outputs.cache-hit != 'true'

      - uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}
          exitZeroOnChanges: false
          autoAcceptChanges: master
          allowConsoleErrors: true
          exitOnceUploaded: true
```

Any ideas? We haven't changed anything on our end ☹️
