### ISSUE TITLE
Accessing the GITHUB_SHA (or any github context) in Storybook from Chroma GitHub Actions

### ISSUE THREAD

**Issue by SiTaggart** [chromaui/chromatic-cli#460]
Hello!

We're building a crude perf monitoring tool on top of Chromatic and Storybook, where we compare React profiler metrics for each story. The final missing piece, for me, is being able to access the git SHA that storybook was built with. I was really hoping I could just set the environment variable in the usual way for GitHub actions, something like:

```yaml
- name: Run Chromatic
  uses: chromaui/action@v1
  env:
    GITHUB_SHA: ${{ secrets.GITHUB_SHA }}
  with:
    projectToken: ${{ secrets.CHROMA_APP_CODE }}
    token: ${{ secrets.GITHUB_TOKEN }}
    buildScriptName: "build:storybook"
    autoAcceptChanges: "main"
    exitOnceUploaded: true
```

Because running and building storybook locally, grabbing `process.env.GITHUB_SHA` when a story is rendered works perfectly.

Alas when I log process.env in the Storybook built by Chromatic, all I get is the following

![image](https://user-images.githubusercontent.com/368249/144364957-dbee39d0-6217-430d-8d1d-cbf4b4afca5d.png)

Is there anyway I can set the environment variable, or get access to it in Stoybook from the github action?
