### ISSUE TITLE
"Invalid --untraced" error

### ISSUE THREAD

**Issue by m0onspell** [chromaui/chromatic-cli#485]
Started getting this:
```
Run chromaui/action@v1

Chromatic CLI v6.3.0
https://www.chromatic.com/docs/cli

✖ Invalid --untraced
This option can only be used in conjunction with --only-changed
→ View the full stacktrace below

If you need help, please chat with us at https://www.chromatic.com/docs/cli for the fastest response.
You can also email the team at support@chromatic.com if chat is not an option.

Please provide us with the above CLI output and the following info:
{
  "timestamp": "2021-12-22T12:19:49.677Z",
  "sessionId": "28c105e1-cd45-4fb4-8bfe-0743016c2920",
  "nodePlatform": "linux",
  "nodeVersion": "12.13.1",
  "packageName": "chromatic",
  "packageVersion": "6.3.0",
  "flags": {
    "projectToken": "***",
    "fromCI": true,
    "interactive": false,
    "exitZeroOnChanges": true,
    "exitOnceUploaded": false,
    "allowConsoleErrors": false
  },
  "errorType": "Error",
  "errorMessage": "✖ Invalid --untraced"
}

Error: ✖ Invalid --untraced
This option can only be used in conjunction with --only-changed
    at /home/runner/work/_actions/chromaui/action/v1/action/main.js:285:517
    at yn (/home/runner/work/_actions/chromaui/action/v1/action/main.js:314:268)
    at gn (/home/runner/work/_actions/chromaui/action/v1/action/main.js:244:246)
    at /home/runner/work/_actions/chromaui/action/v1/action/main.js:350:1609690
    at /home/runner/work/_actions/chromaui/action/v1/action/main.js:350:1608861
    at Object.next (/home/runner/work/_actions/chromaui/action/v1/action/main.js:350:1608966)
    at o (/home/runner/work/_actions/chromaui/action/v1/action/main.js:350:1607680)
Could not retrieve package info from registry; skipping update check
```

in `workflow.yml`:
```yml
      - name: Publish to Chromatic
        if: github.ref != 'refs/heads/main'
        uses: chromaui/action@v1
        # Required options for the Chromatic GitHub Action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        # 👇 Checks if the branch is main and accepts all changes in Chromatic
      - name: Publish to Chromatic and auto accept changes
        if: github.ref == 'refs/heads/main'
        uses: chromaui/action@v1
        # Required options for the Chromatic GitHub Action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: true # 👈 Option to accept all changes
   ```
