### ISSUE TITLE
Slash (/) in branch name disables turbosnap

### ISSUE THREAD

**Issue by IanVS** [chromaui/chromatic-cli#531]
I use the following github action config to enable turbosnap for PRs, but to run full snapshot runs once they are merged to main:

```yml
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
          # Turbosnap if this is not the main branch
          onlyChanged: '!(main)'
          # It's fine if there are visual changes, so long as this is not the main branch
          exitZeroOnChanges: '!(main)'
          # Changes to mock files could change any story, so prevent turbosnap if they change
          externals: mock/**/*.ts
```

However, I've noticed that when I name my branch with a slash, like for instance `issue/951-fix-whatever`, turbosnap does not even attempt to run, as if `onlyChanged` evaluated to false.
