### ISSUE TITLE
Error "not found" using Yarn Berry

### ISSUE THREAD

**Issue by saseungmin** [chromaui/chromatic-cli#578]
Hi! there
I'm using yarn berry(v3.2.0) package manager.
When executing a command in npm, an error occurs that cannot find the command.

It works normally when I change the command that runs in npm to yarn.

```
// before
npm run build-storybook

// after
yarn run build-storybook
```

Who knows how to use github action using "yarn berry"?

I'd appreciate it if anyone could give me some advice. 🙇‍♂️

Here is my chromatic.yml and github action log

```yml
name: 'Chromatic Publish'

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js 16.14.2
        uses: actions/setup-node@v2
        with:
          node-version: "16.14.2"
      - run: yarn install --immutable
      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          skip: 'dependabot/**'
```

```
Chromatic CLI v6.5.4
https://www.chromatic.com/docs/cli

Authenticating with Chromatic
    → Connecting to https://index.chromatic.com
Authenticated with Chromatic
    → Using project token '********cd95'
Retrieving git information
Retrieved git information
    → Commit '545e[7](https://github.com/kasa-network/kasa-web/runs/6609617522?check_suite_focus=true#step:5:8)aa' on branch 'FE-457'; no ancestor found
Collecting Storybook metadata
Collected Storybook metadata
    → ; no supported addons found
Building your Storybook
    → Running command: npm run --silent build-storybook -- --output-dir /tmp/chromatic--1905-1zg5R4T0L17f
The CLI tried to run your build-storybook script, but the command failed. This indicates a problem with your Storybook. Here's what to do:

- Check the Storybook build log printed below.
- Run npm run build-storybook or yarn build-storybook yourself and make sure it outputs a valid Storybook by opening the generated index.html in your browser.
- Review the build-storybook CLI options at https://storybook.js.org/docs/configurations/cli-options/#for-build-storybook

Command failed with exit code 127: npm run --silent build-storybook -- --output-dir /tmp/chromatic--1905-1zg5R4T0L17f

ℹ Spawn settings:
{
  "client": "npm",
  "clientVersion": "[8](https://github.com/kasa-network/kasa-web/runs/6609617522?check_suite_focus=true#step:5:9).5.0",
  "nodeVersion": "v16.14.2",
  "platform": "linux",
  "command": "npm",
  "clientArgs": [
    "run",
    "--silent"
  ],
  "scriptArgs": [
    "build-storybook",
    "--",
    "--output-dir",
    "/tmp/chromatic--1[9](https://github.com/kasa-network/kasa-web/runs/6609617522?check_suite_focus=true#step:5:10)05-1zg5R4T0L[17](https://github.com/kasa-network/kasa-web/runs/6609617522?check_suite_focus=true#step:5:18)f"
  ]
}

ℹ Storybook build output:
/home/runner/work/kasa-web/kasa-web/build-storybook.log

sh: 1: build-storybook: not found
    → Command failed: npm run --silent build-storybook -- --output-dir /tmp/chromatic--[19](https://github.com/kasa-network/kasa-web/runs/6609617522?check_suite_focus=true#step:5:20)05-1zg5R4T0L17f




Error: non-zero exit code
```
