### ISSUE TITLE
Chomatic GH action doens't load presets

### ISSUE THREAD

**Issue by wladiston** [chromaui/chromatic-cli#579]
I'm getting the follow error on my GH actions. It works perfect locally when I ran `npm run chromatic` which makes me think this is a issue different from #570 and others.

I'm currently using the vite builder.

Reproduction repo here:
https://github.com/wladiston/chromatic-vite-ci/tree/master

```sh
Run chromaui/action@v1
  with:
    projectToken: ***
    allowConsoleErrors: true

Chromatic CLI v6.5.4
https://www.chromatic.com/docs/cli

Authenticating with Chromatic
    → Connecting to https://index.chromatic.com
Authenticated with Chromatic
    → Using project token '********1[2](https://github.com/eatingdots/dots-ui/runs/6630301201?check_suite_focus=true#step:6:2)51'
Retrieving git information
Retrieved git information
    → Commit '2[3](https://github.com/eatingdots/dots-ui/runs/6630301201?check_suite_focus=true#step:6:3)b93af' on branch 'master'; found 1 parent build
Collecting Storybook metadata
Collected Storybook metadata
    → ; no supported addons found
Building your Storybook
    → Running command: npm run --silent build-storybook -- --output-dir /tmp/chromatic--2[4](https://github.com/eatingdots/dots-ui/runs/6630301201?check_suite_focus=true#step:6:4)[5](https://github.com/eatingdots/dots-ui/runs/6630301201?check_suite_focus=true#step:6:6)1-ab[6](https://github.com/eatingdots/dots-ui/runs/6630301201?check_suite_focus=true#step:6:7)X6dkrCEWl
The CLI tried to run your build-storybook script, but the command failed. This indicates a problem with your Storybook. Here's what to do:

- Check the Storybook build log printed below.
- Run npm run build-storybook or yarn build-storybook yourself and make sure it outputs a valid Storybook by opening the generated index.html in your browser.
- Review the build-storybook CLI options at https://storybook.js.org/docs/configurations/cli-options/#for-build-storybook

Command failed with exit code 1: npm run --silent build-storybook -- --output-dir /tmp/chromatic--2451-ab6X6dkrCEWl

ℹ Spawn settings:
{
  "client": "npm",
  "clientVersion": "[8](https://github.com/eatingdots/dots-ui/runs/6630301201?check_suite_focus=true#step:6:9).5.5",
  "nodeVersion": "v16.15.0",
  "platform": "linux",
  "command": "npm",
  "clientArgs": [
    "run",
    "--silent"
  ],
  "scriptArgs": [
    "build-storybook",
    "--",
    "--output-dir",
    "/tmp/chromatic--2451-ab6X6dkrCEWl"
  ]
}

ℹ Storybook build output:
/home/runner/work/dots-ui/dots-ui/build-storybook.log

info @storybook/react v6.5.3
info 
info => Cleaning outputDir: /tmp/chromatic--2451-ab6X6dkrCEWl
info => Loading presets
/home/runner/work/dots-ui/dots-ui/node_modules/@storybook/core-server/dist/cjs/utils/server-statics.js:10[9](https://github.com/eatingdots/dots-ui/runs/6630301201?check_suite_focus=true#step:6:10)
    throw new Error((0, _tsDedent.default)((0, _chalk.default)`
          ^
Error: Failed to load static files, no such directory: /home/runner/work/dots-ui/dots-ui/static
Make sure this directory exists, or omit the -s (--static-dir) option.
    at parseStaticDir (/home/runner/work/dots-ui/dots-ui/node_modules/@storybook/core-server/dist/cjs/utils/server-statics.js:[10](https://github.com/eatingdots/dots-ui/runs/6630301201?check_suite_focus=true#step:6:11)9:[11](https://github.com/eatingdots/dots-ui/runs/6630301201?check_suite_focus=true#step:6:12))
    at async /home/runner/work/dots-ui/dots-ui/node_modules/@storybook/core-server/dist/cjs/utils/copy-all-static-files.js:62:34
    → Command failed: npm run --silent build-storybook -- --output-dir /tmp/chromatic--[24](https://github.com/eatingdots/dots-ui/runs/6630301201?check_suite_focus=true#step:6:25)[51](https://github.com/eatingdots/dots-ui/runs/6630301201?check_suite_focus=true#step:6:52)-ab6X6dkrCEWl




Error: non-zero exit code
```

**Comment by tmeasday** [comment]
Hey @wladiston it looks like maybe the working directory might be off? Notice:

> no such directory: /home/runner/work/dots-ui/dots-ui/static

Would you have expected `dots-ui` to be there twice?

**Comment by wladiston** [comment]
No, I don't. `eatingdots` is the company name and `dots-ui` is the repository's name.

I wonder what is causing it. The gh action is very standard and the css seems to be building in the correct directory


```yaml
# Workflow name
name: "Chromatic"

# Event for the workflow
on: push

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history
      - name: 📦 Install dependencies
        uses: borales/actions-yarn@v2.3.0
      - name: 🎨 Build CSS
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build:css
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
```
