### ISSUE TITLE
[github action] Is it possible to add the link to the build result in the GitHub action on PR page?

### ISSUE THREAD

**Issue by ronny1020** [chromaui/chromatic-cli#699]
**Feature request**

Is it possible to add the link to the build result in the GitHub action on the PR page? With the link, we can easier find the build result.

**Proposed solution**

Add a message with the link on the GitHub PR page.

**Additional context**

A message like this kind of message with the link or result.
![image](https://user-images.githubusercontent.com/46809311/207507980-87b068fb-5966-4b77-ae73-21fe22e0d242.png)

**Comment by ghengeveld** [comment]
Hi,

Could you clarify what link you mean exactly? The "build result" could refer to the GitHub Action job, the Chromatic build, or the built / published Storybook.

We currently send 3 commit status updates to pull requests, each with a different Details link:
- Storybook Published - links to your published Storybook
- UI Tests - links to the Chromatic build screen
- UI Review - links to the Chromatic PR screen

We don't post any PR comments like some other tools do. If you feel like this would be a valuable feature, could you elaborate on what you think this message should contain?

**Comment by ronny1020** [comment]
Thanks for the reply. I just can't find any build result link from the result.

![Screen Shot 2022-12-15 at 6 57 20 PM](https://user-images.githubusercontent.com/46809311/207842343-65d1db53-2a5c-4c68-98e1-701e58570cc4.png)

Here is my action file.
```yml
name: 'Chromatic'

on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/install-packages

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
          traceChanged: true

```

Besides, there could be multiple builds in one PR. It would be easier to know which build is from which push with the message.
