### ISSUE TITLE
 chromaui/action UI Review hangs when it is a mandatory check with github merge queue enabled

### ISSUE THREAD

**Issue by adrianbruntonsagecom** [chromaui/chromatic-cli#871]
**Bug report**

Following on from this comment:
https://github.com/chromaui/chromatic-cli/issues/741#issuecomment-1788977333

We are experiencing the same thing.

Our `main` branch protections include:
- Merge queue enabled
- Required checks:
  - Validate / Chromatic
  - UI Review
  - UI Tests
  - Storybook Publish

Snippet of our workflow:
```yaml
# .github\workflows\validate.yml

name: Validate

on:
  pull_request:
  merge_group:

jobs:
  chromatic:
    name: Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: "./.github/actions/install-dependencies"

      - uses: chromaui/action@v10
        id: chromatic
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
```

We'd like to continue using the merge queue as we have historically been. But given we put greater importance on the validation result of "UI Review" and "UI Tests", we've had to disable it for the time being as it is currently hanging and unresponsive, even after the build finishes with all snapshots found.

Appreciate any feedback.

Editing to add screenshots for clarification. This is the view of a completed PR:
![image](https://github.com/chromaui/chromatic-cli/assets/111280016/08687a2a-891a-45af-95ba-5f05fb759cd3)

And this is the merge queue after the PR has been queued:
![image](https://github.com/chromaui/chromatic-cli/assets/111280016/d10f95ea-d1f5-4ec5-ac8a-9564ec5997b3)

As you can see, all checks have completed except for the Chromatic "external" checks which appear to have reset since they were passed on the PR.
