### ISSUE TITLE
Action always passes

### ISSUE THREAD

**Issue by atomicrobokid** [chromaui/chromatic-cli#911]
**Bug report**

Hi, i'm not clear if this is a bug or if i have done something wrong (quite likely) 

My issue is, i've just setup chromatic for the first time, followed all the steps and have set up the github action as below:

```
# .github/workflows/chromatic.yml

name: "Chromatic"

on: pull_request

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        # ⚠️ Pick one of these, matching the package manager for your project
        run: npm ci

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          # ⚠️ Make sure to configure a `CHROMATIC_PROJECT_TOKEN` repository secret
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
```

What i am experiencing is that the action _always_ passes, even though both the action output and the build in chromatic ui identify there are visual changes that need approval. 

Should the action not always require changes to be signed off before passing?

Maybe i've missed an obvious step. 

Finally, is it possible to automatically open a review on chromatic when a pull request is opened? As it stands, for me, that has to be done manually,

Thanks
